mybatis:
  type-aliases-package: cins.art.numproduct.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/numproduct?characterEncoding=utf-8&useSSL=false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
#    database: 0
    jedis:
      pool:
        max-active: -1
        max-idle: 8
        min-idle: 0

server:
  port: 8083